name: Test suite

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }} # Run this job for different versions

    strategy:
      matrix:
        os: [ubuntu-latest] # list of systems to run for. If we build a web-app, usually ubuntu suffices
        python-version: ["3.8", "3.9", "3.10"] # list of python versions. Try to always include the latest version
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Format imports
        run: poetry run isort --profile black --check-only --diff .
      - name: Format code
        run: poetry run black --check .
      - name: Lint code
        run: poetry run flake8
      - name: Static type checking
        run: poetry run mypy
      - name: Run tests
        run: poetry run pytest
