repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
        args: [--unsafe]  # enable unsafe loading for custom tags in mkdocs.yml

-   repo: local
    hooks:
    # matfact
    -   id: flake8
        name: flake8 for matfact
        language: system
        entry: bash -c 'cd matfact && poetry run flake8'
        types: [python]
        files: ^matfact/
    -   id: black
        name: black for matfact
        language: system
        entry: bash -c 'cd matfact && poetry run black .'
        types: [python]
        files: ^matfact/
    -   id: isort
        name: isort for matfact (python)
        language: system
        entry: bash -c 'cd matfact && poetry run isort --profile black .'
        types: [python]
        files: ^matfact/
    -   id: mypy
        name: mypy for matfact
        language: system
        entry: bash -c 'cd matfact && poetry run mypy .'
        types: [python]
        files: ^matfact/

    # hmm_synthetic
    -   id: flake8
        name: flake8 for hmm_synthetic
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run flake8'
        types: [python]
        files: ^hmm_synthetic/
    -   id: black
        name: black for hmm_synthetic
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run black .'
        types: [python]
        files: ^hmm_synthetic/
    -   id: isort
        name: isort for hmm_synthetic (python)
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run isort --profile black .'
        types: [python]
        files: ^hmm_synthetic/
    -   id: mypy
        name: mypy for hmm_synthetic
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run mypy .'
        types: [python]
        files: ^hmm_synthetic/

    # processing
    -   id: flake8
        name: flake8 for processing
        language: system
        entry: bash -c 'cd processing && poetry run flake8'
        types: [python]
        files: ^processing/
    -   id: black
        name: black for processing
        language: system
        entry: bash -c 'cd processing && poetry run black .'
        types: [python]
        files: ^processing/
    -   id: isort
        name: isort for processing (python)
        language: system
        entry: bash -c 'cd processing && poetry run isort --profile black .'
        types: [python]
        files: ^processing/
    -   id: mypy
        name: mypy for processing
        language: system
        entry: bash -c 'cd processing && poetry run mypy .'
        types: [python]
        files: ^processing/

    # bokeh_demo
    -   id: flake8
        name: flake8 for bokeh-demo
        language: system
        entry: bash -c 'cd bokeh-demo && poetry run flake8'
        types: [python]
        files: ^bokeh-demo/
    -   id: black
        name: black for bokeh-demo
        language: system
        entry: bash -c 'cd bokeh-demo && poetry run black .'
        types: [python]
        files: ^bokeh-demo/
    -   id: isort
        name: isort for bokeh-demo (python)
        language: system
        entry: bash -c 'cd bokeh-demo && poetry run isort --profile black .'
        types: [python]
        files: ^bokeh-demo/
    -   id: mypy
        name: mypy for bokeh-demo
        language: system
        entry: bash -c 'cd bokeh-demo && poetry run mypy .'
        types: [python]
        files: ^bokeh-demo/
