repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
        args: [--unsafe]  # enable unsafe loading for custom tags in mkdocs.yml

-   repo: local
    hooks:
    -   id: flake8
        name: flake8 for matfact
        language: system
        entry: bash -c 'cd matfact && poetry run flake8'
    -   id: flake8
        name: flake8 for hmm_synthetic
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run flake8'
    -   id: black
        name: black for matfact
        language: system
        entry: bash -c 'cd matfact && poetry run black .'
    -   id: black
        name: black for hmm_synthetic
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run black .'
    -   id: mypy
        name: mypy for matfact
        language: system
        entry: bash -c 'cd matfact && poetry run mypy .'
    -   id: mypy
        name: mypy for hmm_synthetic
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run mypy .'
    -   id: isort
        name: isort for matfact (python)
        language: system
        entry: bash -c 'cd matfact && poetry run isort --profile black .'
    -   id: isort
        name: isort for hmm_synthetic (python)
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run isort --profile black .'
