exclude: ^(.*/examples|docs)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
        args: [--unsafe]  # enable unsafe loading for custom tags in mkdocs.yml

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        name: flake8

-   repo: https://github.com/psf/black.git
    rev: 22.12.0
    hooks:
    -   id: black
        name: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        name: mypy
        exclude: ^.*/examples

-   repo: local
    hooks:
    -   id: isort
        name: isort for matfact (python)
        language: system
        entry: bash -c 'cd matfact && poetry run isort --profile black .'
    -   id: isort
        name: isort for hmm_synthetic (python)
        language: system
        entry: bash -c 'cd hmm_synthetic && poetry run isort --profile black .'
