exclude: docs
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
        exclude: venv, .git, .pyenv
        ignore: E203, E266, E501, W503, E731
        max-line-length: 88
        max-complexity: 18
        select: B,C,E,F,W,T4


-   repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
    -   id: isort
        name: isort (python)


-   repo: https://github.com/psf/black.git
    rev: 22.12.0
    hooks:
    -   id: black
        name: black


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        name: mypy
