site_name: Decipher

theme:
  name: material
  features: 
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - gen-files:
      scripts: [docs/gen_examples.py]
  - literate-nav:
      nav_file: navigation.md
  - mkdocstrings:
      handlers:
        python:
          paths: [matfact, hmm_synthetic]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
