[tool.poetry]
name = "bokeh-demo"
version = "0.1.0"
description = ""
authors = ["Thorvald Molthe Ballestad <thorvald@simula.no>"]
readme = "README.md"
packages = [{include = "bokeh_demo"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
bokeh = "^2.4.3"
matfact = {path = "../matfact", develop = true}


[tool.poetry.group.dev.dependencies]
mypy = "^0.982"
flake8 = "^5.0.4"
black = {version = "^22.10.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
