# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Lint-and-test:

    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        pip install pre-commit-hooks
        npm install @escape.tech/mookme
    - name: Poetry in matfact
      run: cd matfact && poetry install
    - name: Poetry in HMM
      run: cd hmm_synthetic && poetry install
    - name: Run Mookme
      run: |
        npx mookme run --all -t pre-commit
    - name: Test matfact with pytest
      run: |
        cd matfact && poetry run pytest -Wignore
    - name: Test HMM with pytest
      run: |
        cd hmm_synthetic && poetry run pytest -Wignore
